### PR TITLE
Test also against php 7

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by thiemowmde** [comment]
There is no PHP code in this component, or is it?

**Comment by JeroenDeDauw** [comment]
Not really. Sculpin, which generates the site, is PHP, but then we don't want to test Sculpin

**Comment by bekh6ex** [comment]
Should someone close this PR?

**Comment by manicki** [comment]
Closing. Please re-open if we decide we want to run those checks against PHP 7.

**Pull request closed without merging**
