### PR TITLE
Add ontology.owl for implementing http://wikiba.se/ontology

### PR DESCRIPTION
**Pull request by smalyshev**

### CODE REVIEW

**Comment by Benestar** [comment]
I think someone still needs to deploy this. @JeroenDeDauw?

**Comment by JeroenDeDauw** [comment]
Deployed

**Comment by JeroenDeDauw** [comment]
Seeing this when I hit the thing in FF

derp

Chromium

derp1

**Comment by JeroenDeDauw** [comment]
This fixes it #39

**Pull request merged**
